services:
  nginx:
    image: nginx:alpine
    container_name: portifolio
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html
      - ./docker/local/nginx.conf:/etc/nginx/conf.d/default.conf
